### PR TITLE
Move ingress config to daskhub values.yaml

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
So there is no need to reconfigure the ingress after every change to dask gateway.

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
@guillaumeeb please test

**Comment by guillaumeeb** [comment]
Wow, this would be really cool to have the ingress configured into Helm values.yaml!

Trying this on the current platform I'm trying to deploy (and with an already applied ingress), I get:
```bash
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: Ingress "jupyterhub" in namespace "daskhub" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "daskhub"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "daskhub"
```

**Comment by sebastian-luna-valero** [comment]
Try deleting the previous ingress and reapply the config.

**Comment by guillaumeeb** [comment]
Really nice, that worked! :partying_face: 

This would be much more simple. I propose to take your changes in my PR in order to simplify things, OK for you?

**Comment by sebastian-luna-valero** [comment]
Not a problem.

Closing in favor of

**Pull request closed without merging**
