### PR TITLE
Update EGI Pangeo deployement doc for Elastic and Helm

### PR DESCRIPTION
**Pull request by guillaumeeb**
Related to comments made in #22.

cc @sebastian-luna-valero.

### CODE REVIEW

**Review by sebastian-luna-valero — APPROVED** [review]
Great, many thanks!

Looks good to me!

**Comment by guillaumeeb** [comment]
Thanks for the review @sebastian-luna-valero! I've also added the really cool ingress definition you proposed in #26!

I just need to check your [last comment](https://github.com/pangeo-data/pangeo-eosc/issues/22#issuecomment-1263526208), trying the correct federation service.

**Comment by guillaumeeb** [comment]
This is ready for final review.

**Review by sebastian-luna-valero — APPROVED** [review]
Thanks!

**Pull request merged**
