### PR TITLE
Add Binder

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
Added steps to deploy Dask Gateway alongside Binder

Pending steps:
- [ ] Restrict access to Binder with AAI
- [ ] Deploy container registry to avoid DockerHub rate limits

### CODE REVIEW

**Comment by guillaumeeb** [comment]
Thanks @sebastian-luna-valero for working on this!

If I understand correctly, the end goal is to have:

- In a first namespace: Jupyterhub + dask-gateway (Daskhub)
- In a second one: Binderhub + another dask-gateway set-up.

Is that correct?

**Comment by sebastian-luna-valero** [comment]
Hi @guillaumeeb !

Following the proposal in https://github.com/pangeo-data/pangeo-eosc/issues/25#issuecomment-1265035408 I am using a single namespace to deploy:
* Binderhub first
* Adding dask-gateway later on

Did I interpret Sarah's comment correctly? Do you foresee issues?

**Comment by guillaumeeb** [comment]
No I think it will be fine if you deploy Binderhub and Jupyterhub in a different namespace.

I was just saying that this means having two dask-gateway server in two different namespaces, but this is actualy no big deal and certainly much simpler!!

**Comment by sebastian-luna-valero** [comment]
Closing in favor of: https://github.com/pangeo-data/pangeo-eosc/pull/54

**Pull request closed without merging**
