### PR TITLE
Add pangeo-escience object store

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
New OpenStack project and Check-In group available.

Please remember that attendees for the eScience workhop need to be added to the `pangeo.escience` group in Check-In:
https://docs.egi.eu/users/aai/check-in/vos/#adding-members-to-vo-groups

### CODE REVIEW

**Comment by annefou** [comment]
Thanks Sebastian. I don't think I am an admin for Pangeo prod (only for the dev) so I cannot see and approve the petitions and add users to pangeo-escience.

**Comment by annefou** [comment]
> Thanks Sebastian. I don't think I am an admin for Pangeo prod (only for the dev) so I cannot see and approve the petitions and add users to pangeo-escience.

Sorry I was not looking at the right "place". Students and mentors haven't enrolled to the pangeo prod yet and this is what I could not approve anyone!

**Review by guillaumeeb — APPROVED** [review]
Thanks @sebastian-luna-valero! This looks perfect.

**Comment by guillaumeeb** [comment]
Hm, not sure why, but I don't have management rights on this repository anywore.

@annefou I suspect that there has been cleaning of permissions at Pangeo steering council level (which is perfectly normal), I previously had every rights on all Pangeo repo, but I don't have anymore.

**Pull request merged**
